import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/shared/Navbar'
import { ToastContainer } from 'react-toastify'
import Footer from '@/components/shared/Footer'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="light">
      <body className={inter.className}>
        <div>
        <Navbar/>
        <ToastContainer />
        <div className='z-0'>
        {children}
        </div>
        <Footer/>
        </div>
        </body>
    </html>
  )
}
